[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/mocks=lib/openzeppelin-contracts/contracts/mocks"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
